/*
    (c) 2018 tevador <tevador@gmail.com>

    This file is part of Tevador.RandomJS.

    Tevador.RandomJS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Tevador.RandomJS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Tevador.RandomJS.  If not, see<http://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Linq;
using System.Net;
using Tevador.RandomJS.Operators;

namespace Tevador.RandomJS
{
    class Program : Block, IProgram
    {
        private Dictionary<string, Global> _globalNames = new Dictionary<string, Global>();
        private List<Global> _globals = new List<Global>();
        private List<Variable> _printOrder;
        private ProgramOptions _options;
        private WebClient _client;

        public Program()
            : base(null)
        {

        }

        public override void Require(Global gl)
        {
            if (!_globalNames.ContainsKey(gl.Name))
            {
                _globalNames.Add(gl.Name, gl);
                var gfunc = gl as GlobalFunction;
                if (gfunc?.References != null)
                {
                    Require(gfunc.References);
                }
                _globals.Add(gl);
            }
        }

        public override ProgramOptions Options
        {
            get { return _options; }
        }

        private void SetGlobalVariable<T>(string name, T value)
        {
            if (value != null && _globalNames.TryGetValue(name, out Global g))
            {
                GlobalVariable glVar = g as GlobalVariable;
                if (glVar != null)
                {
                    glVar.Initializer = new Expressions.Literal(value.ToString());
                }
            }
        }

        public Program Generate(IRandom rand, ProgramOptions options)
        {
            _options = options;
            rand.Seed(options.Seed);
            if (_options.DepthProtection != null)
                _options.DepthProtection?.AttachTo(this);
            while (_declaredVariables.Count < options.GlobalVariablesCount)
            {
                _declaredVariables.Add(Variable.Generate(rand, this, false, false));
            }
            _printOrder = new List<Variable>(_declaredVariables);
            rand.Shuffle(_printOrder);
            foreach (var v in _printOrder)
            {
                _statements.Add(OutputStatement.Generate(rand, this, v));
            }
            SetGlobalVariable(GlobalFunction.STRL.References.Name, _options.MaxStringVariableLength);
            return this;
        }

        public override void WriteTo(System.IO.TextWriter w)
        {
            w.WriteLine("/* This program was generated by Tevador.RandomJS */");
            w.WriteLine("/* {0} */", _options);
            w.WriteLine("/* globals: */");
            foreach (var gf in _globals)
            {
                gf.WriteTo(w);
            }
            w.WriteLine("/* Print order: {0} */", string.Join(", ", _printOrder));
            base.WriteTo(w);
        }

        // 4,86236203379662 ms per seed
        // Runtime: Min: 2,1137; Max: 22,169; Avg: 3,90796864137288; Stdev: 1,87134841989214;
        public int Execute(out string output, out string error)
        {
            var client = _client ?? (_client = new WebClient());
            StringBuilder sb = new StringBuilder(10000);
            using (var writer = new StringWriter(sb))
            {
                WriteTo(writer);
            }
            try
            {
                output = client.UploadString("http://localhost:18111", sb.ToString());
                error = null;
                return 0;
            }
            catch(WebException e)
            {             
                output = null;
                var response = e.Response as HttpWebResponse;
                if (response != null)
                {
                    error = new StreamReader(response.GetResponseStream()).ReadToEnd();
                    return (int)response.StatusCode;
                }
                else
                {
                    error = e.Message;
                    return e.HResult;
                }
            }
        }

        public byte[] Seed
        {
            get { return _options.Seed; }
        }

        static unsafe byte[] GenerateSeed(int init)
        {
            ulong smallSeed = (ulong)init;
            byte[] bigSeed = new byte[4 * sizeof(ulong)];
            fixed (byte* buffer = bigSeed)
            {
                ulong* s = (ulong*)buffer;
                s[0] = Xoshiro256Plus.SplitMix64(ref smallSeed);
                s[1] = Xoshiro256Plus.SplitMix64(ref smallSeed);
                s[2] = Xoshiro256Plus.SplitMix64(ref smallSeed);
                s[3] = Xoshiro256Plus.SplitMix64(ref smallSeed);
            }
            return bigSeed;
        }

        static void MakeStats(IRandom random, ProgramOptions options)
        {
            const int count = 10000;
            var runtimes = new List<double>(count);

            var sw = Stopwatch.StartNew();
            var runtimeSw = new Stopwatch();
            for (int i = 0; i < count; ++i)
            {
                var seed = Environment.TickCount + i;
                Console.WriteLine("Seed = {0}", seed);
                options.Seed = GenerateSeed(seed);
                var p = new Program();
                p.Generate(random, options);
                runtimeSw.Restart();
                var exitCode = p.Execute(out string output, out string error);
                runtimeSw.Stop();
                if (exitCode != 0)
                {
                    Console.WriteLine($"// ExitCode = {exitCode}");
                    Console.WriteLine(output);
                    Console.WriteLine(error);
                    break;
                }
                runtimes.Add(runtimeSw.Elapsed.TotalMilliseconds);
            }
            sw.Stop();

            Console.WriteLine($"// {count} seeds processed in {sw.Elapsed.TotalSeconds} seconds");

            runtimes.Sort();
            runtimes.RemoveAt(0);
            runtimes.RemoveAt(runtimes.Count - 1);
            var avg = runtimes.Average();
            var min = runtimes[0];
            var max = runtimes[runtimes.Count - 1];
            var sqsum = runtimes.Sum(d => (d - avg) * (d - avg));
            var stdev = Math.Sqrt(sqsum / runtimes.Count);
            Console.WriteLine($"Runtime: Min: {min}; Max: {max}; Avg: {avg}; Stdev: {stdev};");
            int[] histogram = new int[(int)Math.Ceiling((max - min) / stdev * 10)];
            foreach (var run in runtimes)
            {
                histogram[(int)(((run - min) / stdev * 10))]++;
            }
            Console.WriteLine("Histogram:");
            for (int j = 0; j < histogram.Length; ++j)
            {
                Console.WriteLine(string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0} {1}", j * stdev / 10 + min, histogram[j]));
            }
        }

        static void Main(string[] args)
        {
            if(args.Length == 0 || !int.TryParse(args[0], out int seed))
            {
                seed = Environment.TickCount;
            }

            var random = new Xoshiro256Plus();

            var options = new ProgramOptions()
            {
                AssignmentOperators = new RandomTable<AssignmentOperator>()
                {
                    { 0.15, AssignmentOperator.Add },
                    { 0.05, AssignmentOperator.Sub },
                    { 0.05, AssignmentOperator.Mul },
                    { 0.05, AssignmentOperator.Div },
                    { 0.04, AssignmentOperator.Rem },
                    { 0.7, AssignmentOperator.Mov },
                    { 0.2, AssignmentOperator.PreInc },
                    { 0.2, AssignmentOperator.PostDec },
                    { 0.2, AssignmentOperator.PreDec },
                    { 0.2, AssignmentOperator.PostInc },
                },
                BinaryOperators = new RandomTable<BinaryOperator>()
                {
                    { 0.4, BinaryOperator.Add },
                    { 0.1, BinaryOperator.Sub },
                    { 0.1, BinaryOperator.Mul },
                    { 0.1, BinaryOperator.Div },
                    { 0.1, BinaryOperator.Rem },
                    { 0.1, BinaryOperator.Equal },
                    { 0.1, BinaryOperator.NotEqual },
                    { 0.05, BinaryOperator.Min },
                    { 0.05, BinaryOperator.Max },
                    { 0.1, BinaryOperator.Xor },
                    { 0.1, BinaryOperator.Less },
                    { 0.1, BinaryOperator.Greater },
                    { 0.1, BinaryOperator.Comma },
                },
                UnaryOperators = new RandomTable<UnaryOperator>()
                {
                    { 0.05, UnaryOperator.Plus },
                    { 0.1, UnaryOperator.Typeof },
                    { 0.2, UnaryOperator.Minus },
                    { 0.2, UnaryOperator.Not },
                    { 0.2, UnaryOperator.Sqrt },
                    { 0.05, UnaryOperator.Exp },
                    { 0.05, UnaryOperator.Log },
                    { 0.05, UnaryOperator.Sin },
                    { 0.05, UnaryOperator.Cos },
                    { 0.05, UnaryOperator.Atan },
                    { 0.05, UnaryOperator.Floor },
                    { 0.05, UnaryOperator.Ceil },
                },
                ConstVariableChance = 0.1,
                //DepthProtection = new CallDepthProtection(5),
                GlobalVariablesCount = 10,
                MaxExpressionDepth = 5,
                MaxStatementDepth = 2,
                MaxFunctionParameterCount = 3,
                MaxStringLiteralLength = 10,
                FuncInvocationInExprChance = 0.25,
                MaxStringVariableLength = 20,
                Seed = GenerateSeed(seed),
                Literals = new RandomTable<LiteralType>()
                {
                    { 0.2, LiteralType.String },
                    { 0.8, LiteralType.Numeric }
                },
                NumericLiterals = new RandomTable<NumericLiteralType>()
                {
                    { 0.125, NumericLiteralType.Boolean },
                    { 0.125, NumericLiteralType.DecimalInteger },
                    { 0.05, NumericLiteralType.BinaryInteger },
                    { 0.125, NumericLiteralType.OctalInteger },
                    { 0.125, NumericLiteralType.SmallInteger },
                    { 0.125, NumericLiteralType.HexInteger },
                    { 0.125, NumericLiteralType.FixedFloat },
                    { 0.125, NumericLiteralType.ExpFloat },

                },
                Expressions = new RandomTable<ExpressionType>()
                {
                    { 0.13, ExpressionType.AssignmentExpression },
                    { 0.15, ExpressionType.BinaryExpression },
                    { 0.2, ExpressionType.FunctionExpression },
                    { 0.1, ExpressionType.Literal },
                    { 0.05, ExpressionType.TernaryExpression },
                    { 0.07, ExpressionType.UnaryExpression },
                    { 0.1, ExpressionType.VariableInvocationExpression },
                }
            };

            Program p = new Program().Generate(random, options);
            p.WriteTo(Console.Out);
            Console.WriteLine($"// {random.Counter} random numbers used");
        }
    }
}
